### PR TITLE
API test coverage

### PR DESCRIPTION
**Pull request by mkudlej**
I've tried to describe in this specification need for comparing couple of different sources for API function lists.

### CODE REVIEW

**Comment by mkudlej** [comment]
@brainfunked @anivargi Please review.

**Comment by r0h4n** [comment]
@mkudlej whats the status of this one, seems stale

**Comment by fbalak** [comment]
We have parsing scripts but they are deprecated now and we need to update them with new paths for definition files and our testing framework. There are now tasks with higher priority that we are working on. We will revisit this item after they will be done.

**Comment by r0h4n** [comment]
Any updates on this?

**Comment by fbalak** [comment]
@r0h4n We have some [script](https://github.com/fbalak/apistate/blob/master/apistate.py) used in downstream. It generates table from [usmqe-tests](https://github.com/Tendrl/usmqe-setup) and [api](https://github.com/Tendrl/api) repos. It lists api calls covered in our framework, in our tests and documented calls.

**Comment by r0h4n** [comment]
I am going to close this one, if required open another spec with specific dates and targets

**Pull request closed without merging**
