### PR TITLE
Spec for new disk inventory structure in etcd 

### PR DESCRIPTION
**Pull request by GowthamShanmugam**

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @nnDarshan @shtripat @nthomas-redhat @brainfunked please review

**Comment by GowthamShanmugam** [comment]
@r0h4n @brainfunked @shtripat @nnDarshan @nthomas-redhat serial number and vendor_id and manufacturing_id is not available for VM disks  from hwinfo

Please give some alternate form that

one more doubt is 

vdb                          252:16   0   15G  0 disk  
└─mygroup-mythinpool_tdata   253:3    0    2G  0 lvm   
  └─mygroup-mythinpool-tpool 253:4    0    2G  0 lvm   
    ├─mygroup-mythinpool     253:5    0    2G  0 lvm   
    ├─mygroup-thinv1         253:6    0    1G  0 lvm   
    └─mygroup-thinv2         253:7    0  500M  0 lvm   
vdc                          252:32   0   15G  0 disk  
└─mygroup-mythinpool_tmeta   253:2    0    4M  0 lvm   
  └─mygroup-mythinpool-tpool 253:4    0    2G  0 lvm   
    ├─mygroup-mythinpool     253:5    0    2G  0 lvm   
    ├─mygroup-thinv1         253:6    0    1G  0 lvm   
    └─mygroup-thinv2         253:7    0  500M  0 lvm   

if you see here lvm thinv1 and thinv2 details is in same Volume Group but as per current disk structure is suggested will store   thinv1 and thinv2  under vdb and vdc also. is this correct?

**Comment by r0h4n** [comment]
Is this a duplicate spec of https://github.com/Tendrl/specifications/pull/156 ?

**Comment by GowthamShanmugam** [comment]
@r0h4n yes

**Comment by GowthamShanmugam** [comment]
@r0h4n i can't update @nnDarshan PR so i have done changes and sent as new PR

**Comment by GowthamShanmugam** [comment]
@brainfunked @r0h4n @shtripat @nnDarshan  hwinfo gives 
 Device Files: /dev/vdh, /dev/disk/by-id/virtio-78065dbf-92db-4574-8, /dev/disk/by-path/virtio-pci-0000:00:0e.0
here  /dev/disk/by-id/virtio-78065dbf-92db-4574-8 is never change for that particular disk even disk name change when we do deactivate disk.
we can use this, but problem is for real machine it gives two id
like 
Device Files: /dev/sda, /dev/disk/by-id/ata-SAMSUNG_MZ7TE512HMHP-000L1_S1GJNSAG400778, /dev/disk/by-id/wwn-0x4d30445853885002

both format looks different

**Comment by GowthamShanmugam** [comment]
@r0h4n As per mrugesh suggestion i have updated old disk spec file and i have sent that as new PR, So this PR is not required.

**Pull request closed without merging**
