### PR TITLE
Tendrl threshold event generation

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bugid: Tendrl/specifications#239

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @anmolbabu @nnDarshan @brainfunked @nthomas-redhat @anivargi @rishubhjain please review

**Review by shtripat — COMMENTED** [review]
Based on yesterday's discussion in daily meeting, this need changes I feel as no events from `gluster-integration`. Anyway cross verify with Rohan and do the needful here.

**Comment by GowthamShanmugam** [comment]
@brainfunked this spec is not required am i close this PR

**Comment by GowthamShanmugam** [comment]
@r0h4n i feel this spec is not required, we can close this

**Pull request closed without merging**
